# Generated by Django 3.1 on 2020-08-09 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRepaymentAmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('no_repayments', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('monthly_repayment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['created', 'loan_amount', 'no_repayments', 'monthly_repayment_amount'],
            },
        ),
    ]
